baseurl = "https://username.github.io"
DefaultContentLanguage = "en"
title = "Pan Feng"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "Pan Feng 的博客" # Set a different text for the header on the home page
  subtitle = "测试用"
  logo = "avatar/tom.jpg" # 网站头像
  # logo = "avatar/pan.png" # 网站头像
  favicon = "avatar/favicon.ico" # 网站图标
  dateFormat = "Jan 2 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Pan Feng11"  # 首页结尾署名
  website = "yourwebsite.com"
  email = "youremail@domain.com"
#   facebook = "username"
#   googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
#   github = "username"
#   gitlab = "username"
#   bitbucket = "username"
#   twitter = "username"
#   reddit = "username"
#   linkedin = "username"
#   xing = "username"
#   stackoverflow = "users/XXXXXXX/username"
#   snapchat = "username"
#   instagram = "username"
#   youtube = "user/username" # or channel/channelname
#   soundcloud = "username"
#   spotify = "username"
#   bandcamp = "username"
#   itchio = "username"
#   vk = "username"
#   paypal = "username"
#   telegram = "username"
#   500px = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 10

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 40

[[menu.main]]
    identifier = "samples"
    name = "Samples"
    weight = 30

[[menu.main]]
    parent = "samples"
    name = "Big Image Sample"
    url = "post/dir/"
    weight = 31

[[menu.main]]
    parent = "samples"
    name = "Math Sample"
    url = "机器学习/"
    weight = 32

[[menu.main]]
    parent = "samples"
    name = "Code Sample"
    url = "post/2016-03-08-code-sample"
    weight = 33

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 20
